import "@components/navbar.component";
import "@components/navbar-item.component";
import "@components/button.component";
import "@components/table.component";
import "@components/content.component";
import "@components/input.component";
import "./atoms/spacing.scss";
import "./atoms/colors.scss";
import "./atoms/seizes.scss";
